# setup command prefix
unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix

# options
set -g mouse on
set -g default-terminal "tmux-256color"

# plugins

# Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'

# Tmux Resurrect
# prefix + Ctrl-s - save
# prefix + Ctrl-r - restore
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

# Load catppuccin plugin
# set -g @plugin 'catppuccin/tmux#v2.1.3'
# run ~/.tmux/plugins/tmux/catppuccin.tmux
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Configure catppuccin plugin
set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "rounded"
set -g status-left ""
set -g status-right "#{pane_title} | #(date '+%H:%M')"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
# set -g window-status-format "#[fg=#dce0e8,bg=#{@thm_overlay_2}] #I #[fg=#4c4f69,bg=#{@thm_surface_0}] #W "
# set -g window-status-current-format "#[fg=#dce0e8,bg=#{@thm_mauve}] #I #[fg=#4c4f69,bg=#{@thm_surface_1}] #W "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
